---
stages:
- name: Jenkins Trigger
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Worker
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      # curl JENKINS_URL/job/Build&Deploy/build?token=TOKEN_NAME
- name: Jenkins Finished Hook
  jobs:
  - name: Worker
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      echo 'Jenkins build & deploy finished'