---
stages:
- name: Jenkins Trigger
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Worker
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      curl JENKINS_URL/job/Build%26Deploy/build?token=jenkins_sample_app
- name: Jenkins Success Hook
  jobs:
  - name: Worker
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      echo 'Jenkins build & deploy finished successfully'
- name: Jenkins Failure Hook
  jobs:
  - name: Worker
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      echo 'Jenkins build & deploy failed'